### Problem Statement - Finding Information Technology open positions in Hyderabad location

In [1]:
#Identify Key Tech Hires in the Hyderabad area -
#Companies (both international and local) competing for local talent pool.
#Our aim is to Identify the key Companies in the market who are hiring in Hyderabad area.
#When you have those, we want to know how many positions they have and what are the Key skills they are hiring for.
#Your output file may look like this
#Name of the company, Number of Positions , Segmentation, Skills they are looking for
#============================================================
#Amazon, 2300, “Information technology” , “Tableau, R, Python, Java, Salesforce”
#Flipkart, 1300, “Information technology” , “Java, API, REST API, Integration, C++, Python”
#Microsoft, 8600, “information technology”, “.net, Machine Learning, AI, Tableau”

In [69]:
from selenium import webdriver
import chromedriver_binary
import time
import pandas as pd 
import datetime
import urllib.request
import warnings

#### Scraping naukri.com...

In [70]:
urllink = "https://www.naukri.com/information-technology-jobs-in-hyderabad-secunderabad" # URL to scrape
warnings.filterwarnings('ignore') # to ignore any warnings
pd.set_option('display.max_colwidth', 100) # to display dataframe column data upto 100 characters

#### Ask for chrome driver location

In [71]:
#driverlocation = "D:/Softwares/chromedriver_win32/chromedriver.exe"
driverlocation = input("Enter the location of Chrome Driver: ")

Enter the location of Chrome Driver: D:/Softwares/chromedriver_win32/chromedriver.exe

#### Lets get the input from user to scrape the number of pages. The higher the number, the longer the time it takes to scrape...

In [72]:
pages_to_scrape = input("Enter the number(int) of pages to scrape: ")

# Exception handling for the input

try:
    pages_to_scrape = int(pages_to_scrape)
except ValueError:
    try:
        pages_to_scrape = int(round(float(pages_to_scrape)))
        print("Input is a float  number so it's interger value will be considered i.e. ", pages_to_scrape)
    except ValueError:
        print("Input is not a number. No need to proceed...")

Enter the number(int) of pages to scrape: 10

#### Define empty lists for required attributes and then populate the same in a loop...

In [81]:
driver = webdriver.Chrome(driverlocation)

company_name = [] # empty list to be populated with company names
designation = [] # empty list to be populated with designations
skills = [] # empty list to be populated with skills

jobs_per_page = 20  # There are 20 job postings on any naukri.com page

for i in range(0,pages_to_scrape):   
    if i==0:
        urlToBrowse = urllink
    else:
        urlToBrowse = urllink + "-" + str(i+1)  # adding page number with '-' from 2nd page onwards
        
    driver.get(urlToBrowse)
    
    for j in range(1,jobs_per_page+1):
        company_name.append(driver.find_element_by_xpath( \
            '//*[@id="root"]/div[4]/div[2]/section[2]/div[2]/article['+str(j)+']/div[1]/div/div/a[1]').text)
        designation.append(driver.find_element_by_xpath( \
            '//*[@id="root"]/div[4]/div[2]/section[2]/div[2]/article['+str(j)+']/div[1]/div/a').text)
        skills.append(driver.find_element_by_xpath( \
            '//*[@id="root"]/div[4]/div[2]/section[2]/div[2]/article['+str(j)+']/ul').text)
        time.sleep(1)
    time.sleep(5)
    
driver.close() # Closing the driver

#print(company_name)
#print(designation)
#print(skills)

#### Create a dataframe with columns as the lists populated above

In [82]:
df_jobs = pd.DataFrame()
df_jobs["company_name"] = company_name
df_jobs["designation"] = designation
df_jobs["skills"] = skills
df_jobs

,company_name,designation,skills
0,Nisarga Information Technology Solutions Pvt Ltd,Business Development Manager,Communication Skills\nSales\nBusiness Development Management
1,Cognia Technologies,Information Technology (.Net),assembly language\nSix Sigma\nJavaScript\nReal Time Operating Systems\n.NET\nHTML\nOracle\nPython
2,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY),INFORMATION TECHNOLOGY\nGeneral Manager IT\nDebugging\nTools\nJ2Ee\nWindows\nApplication software
3,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY),Computer science\nmanagement information system\nINFORMATION TECHNOLOGY\nLinux\nGENERAL MANAGER\...
4,TERRA TECHNOLOGY,Information Technology,Unix\nService management\nglobal operations\nLinux\nAnalytical\nWindows\nCustomer service\nInfor...
...,...,...,...
195,Wells Fargo India Solutions Pvt. Ltd.,Apps Systems Engineer 4,Computer science\nBusiness services\nConflict resolution\nagile project management\nTime managem...
196,Wells Fargo India Solutions Pvt. Ltd.,Apps Systems Engineer 4,Computer science\nBusiness services\nConflict resolution\nagile project management\nTime managem...
197,Wells Fargo India Solutions Pvt. Ltd.,Apps Systems Engineer 6,Computer science\nBusiness services\nConflict resolution\nagile project management\nTime managem...
198,Wells Fargo India Solutions Pvt. Ltd.,Apps Systems Engineer 6,Computer science\nAutomation\nConflict resolution\nagile project management\nRetail banking\nScr...
199,Wells Fargo India Solutions Pvt. Ltd.,Apps Systems Engineer 5,Computer science\nAutomation\nConflict resolution\nagile project management\nRetail banking\nScr...

#### Groupby the dataframe by 'company_name' and concatenate 'designation' and 'skills'. Use delimiter as '|-|' to avoid any occurence in data

In [83]:
df_jobs_agg = df_jobs.groupby(['company_name'],as_index=False)['designation','skills'].agg('|-|'.join)
df_jobs_agg

,company_name,designation,skills
0,AGI INDUSTRIES PRIVATE LIMITED,it-networking-manager,switching\nhr recruiter\nnetwork engineering\ninformation technology\nsoftware\nhiring\nites\nit...
1,"Advanced Micro Devices, Inc.",Network-Engineer-1-1,Telecom\nNetworking\nWAN\nNetwork security\nCCNA\nTroubleshooting\nInformation technology\ncisco
2,Ayan Consultancy,Project Manager,Project analysis\nProject management\nBudgeting\nInformation technology
3,BM Global Solutions,Visio Tool Expert (Freelance),freelance\nMS Visio\nIT\nInformation Technology
4,CDK GLOBAL (INDIA) PRIVATE LIMITED,Automation Engineer - Python,IT Skills\nPython\nSoftware Development\nJavascript\nSalesforce\nAutomation\nLinux\nJavascript
5,"CDK GLOBAL, LLC.",Automation Engineer - Python,Linux\nJavascript\nFlex\nWorkflow\nPerl\nDigital marketing\nInformation technology\nAutomotive
6,Cognia Technologies,Information Technology (.Net),assembly language\nSix Sigma\nJavaScript\nReal Time Operating Systems\n.NET\nHTML\nOracle\nPython
7,Comint Systems and Solutions Pvt Ltd,"NETWORK ENGINEERS, CUSTOMER SUPPORT ENGINEERS",Telecom\nNetworking\nBusiness expansion\nElectronics\nNetwork security\nInstrumentation\nSupport...
8,Cubic Transportation Systems India Pvt. Ltd.,Senior Software Engineer|-|Principal Lead Software Engineer|-|Senior Software Engineer,Computer science\nHibernate\nNetworking\nCoding\nDebugging\nSupport services\nUnit testing\nTrou...
9,Dhruvsoft Services Pvt Ltd,Fresher / Entry Level Position For Software Engineer - Hyderabad,Entry Level\nApplication Programming\nSoftware Engineering\nB.E\nIT\nInformation Technology
10,Edification Technologies,Software Developer,Angularjs\nit development\nsoftware development\ninformation technology development\nIonic Frame...
11,ExecBoardinAsia,Sr. Engineer,operational support\nPublishing\nVideo conferencing\nScheduling\nmicrosoft\nIT operations\ncisco...
12,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY)|-|GENERAL MANAGER (INFORMATION TECHNOLOGY),INFORMATION TECHNOLOGY\nGeneral Manager IT\nDebugging\nTools\nJ2Ee\nWindows\nApplication softwar...
13,International Institute of Information Technology,Technology Management- Lecturer|-|Technology Management- Assistant Professor|-|Technology Manage...,Counselor\nMentor\nTrainer\nAdvisor\nEducator\nTeaching|-|Counselor\nMentor\nTrainer\nAdvisor\nE...
14,Karvy Group,Head - Information Technology,Head Information Technology
15,Lincoln Tech,Software Engineer,Computer science\ninformation system\nSystem management\nDatabase management\nManagement systems...
16,MINDCRAFT TRAININGS,"Online Teacher(Hiring For PAN India location, WFH)",Application Programming\nJava\nC++\nCSS\nC\nSoftware Testing\nHTML\nManual Testing
17,Medinovix,Software Engineer (Fresher),Computer science\ninformation system\nSystem management\nDatabase management\nManagement systems...
18,MetrixLab,Security Engineer\Analyst|-|Security Engineer\Analyst,Unix\nLinux\nNetworking\nVPN\nNetwork security\nHTTP\nSelenium\nCCNA|-|Unix\nLinux\nNetworking\n...
19,Nisarga Information Technology Solutions Pvt Ltd,Business Development Manager,Communication Skills\nSales\nBusiness Development Management
20,Novartis Healthcare Pvt. Ltd.,DevSecOps & Automation Engineer,Networking\nWAN\nLAN\nActive directory\nDNS\nTroubleshooting\nRuby\nInformation technology
21,Overseas Information Technology,"Opening For Appian Developer/L1 or L2 MUST--Bangalore, Hyderabad, Pune|-|Urgent Opening For Appi...",appian\nL1\nL2\nlevel 2|-|Client Communication\nAgile\nScrum\nProcess Design\nJIRA\nLeadership S...
22,Personal Network. Ltd,Software Engineer / Sr. Software Engineer - RDBMS,Senior Design Engineer\nTechnology consulting\nNetworking\nRDBMS\nPLSQL\nPRO*C\nInformation tech...
23,R G F Services,AI ML Architect,Architecture\nSystem Design\nAnalytical\nHTTP\nMachine Learning\nInformation technology
24,Ram IT Solutions,US HR Operations Trainee | HR,IT services\nService management\nPerformance management\nInfrastructure management\nEmployee eng...
25,S2TECH.COM INDIA PVT LTD,NIT / IIT Freshers For Trainee - Software Engineer Immediate Position,Design\ninformation technology engineering\nCoding\nSoftware Engineering\nit engineering
26,SG Analytics Pvt. Ltd.,Contract To Hire - ( Secondary Research - IT/ Telecom),Telecom\nSecondary Research\nCompany Analysis\nAdvanced Excel\nIT\nReport Writing\nSWOT\nBalance...
27,Sahasya Global Solutions,Product Support Engineer,technical\nsoftware\nSystem programming\ntesting\nit\nTroubleshooting\nInformation technology\nP...
28,Stellar Information Technology Private Limited,Relationship Manager || IT Product Sales Exp. (1-4 Yrs.),CRM Sales\nIt Product Sales\nB2B Sales\nHardware Sales\nIT Sales\nIT Hardware Sales\nCloud Sales...
29,TERRA TECHNOLOGY,Information Technology|-|Information Technology,Unix\nService management\nglobal operations\nLinux\nAnalytical\nWindows\nCustomer service\nInfor...
30,TOOURS COM,Sales and Business Development - Internship,Business administration\nEconomics\nPDF\nNetworking\nWorkflow\nHTML\nAfter sales support\nB2B Sales
31,Thinksure Information Technology Private Limited,Dot Net Developer-Permanent|-|.Net Developer - Agreement with the Client For span of 2 Years,.Net|-|asp.net mvc\nlinq\nc#.net\nsql server\nasp net
32,Times World Information Technology,Area Business Manager/Project Manager,Area Business Manager/Project Manager
33,True Troops Consultants Private Limited,IT Freshers and Software Developers|-|IT Engineer,Java\nfresher\nC++\nEngineering graduates\nB tech freshers\nC#.Net\n.Net\nASP.Net|-|it engineer\...
34,Wells Fargo India Solutions Pvt. Ltd.,Systems Support Analyst 1|-|Senior Technology Specialist|-|Senior Technology Specialist|-|Techno...,SAN\nRedhat\nNetworking\nRDBMS\nShell scripting\nSSH\nWindows\nInformation technology|-|Unix\nRe...
35,Young India Information Technology Services (P) Lt,Syteline Techno Functional Analysts|-|Syteline Technical Developers|-|IT Sales Manager,Training\nBusiness Analyst\nTechno functional\nDesign development\nPresales\nProposal building|-...
36,Zyme India,Associate / Global Support Engineer,Computer science\nBusiness process\nTomcat\nLinux\nProduction support\nJBoss\nConfiguration mana...

#### Add a new attribute for number of positions. Populate with the number of values in aggregated 'designation' attribute (separated by '|-|')

In [84]:
df_jobs_agg["number_of_positions"] =  df_jobs_agg['designation'].apply(lambda i: len(i.split('|-|')))
df_jobs_agg

,company_name,designation,skills,number_of_positions
0,AGI INDUSTRIES PRIVATE LIMITED,it-networking-manager,switching\nhr recruiter\nnetwork engineering\ninformation technology\nsoftware\nhiring\nites\nit...,1
1,"Advanced Micro Devices, Inc.",Network-Engineer-1-1,Telecom\nNetworking\nWAN\nNetwork security\nCCNA\nTroubleshooting\nInformation technology\ncisco,1
2,Ayan Consultancy,Project Manager,Project analysis\nProject management\nBudgeting\nInformation technology,1
3,BM Global Solutions,Visio Tool Expert (Freelance),freelance\nMS Visio\nIT\nInformation Technology,1
4,CDK GLOBAL (INDIA) PRIVATE LIMITED,Automation Engineer - Python,IT Skills\nPython\nSoftware Development\nJavascript\nSalesforce\nAutomation\nLinux\nJavascript,1
5,"CDK GLOBAL, LLC.",Automation Engineer - Python,Linux\nJavascript\nFlex\nWorkflow\nPerl\nDigital marketing\nInformation technology\nAutomotive,1
6,Cognia Technologies,Information Technology (.Net),assembly language\nSix Sigma\nJavaScript\nReal Time Operating Systems\n.NET\nHTML\nOracle\nPython,1
7,Comint Systems and Solutions Pvt Ltd,"NETWORK ENGINEERS, CUSTOMER SUPPORT ENGINEERS",Telecom\nNetworking\nBusiness expansion\nElectronics\nNetwork security\nInstrumentation\nSupport...,1
8,Cubic Transportation Systems India Pvt. Ltd.,Senior Software Engineer|-|Principal Lead Software Engineer|-|Senior Software Engineer,Computer science\nHibernate\nNetworking\nCoding\nDebugging\nSupport services\nUnit testing\nTrou...,3
9,Dhruvsoft Services Pvt Ltd,Fresher / Entry Level Position For Software Engineer - Hyderabad,Entry Level\nApplication Programming\nSoftware Engineering\nB.E\nIT\nInformation Technology,1
10,Edification Technologies,Software Developer,Angularjs\nit development\nsoftware development\ninformation technology development\nIonic Frame...,1
11,ExecBoardinAsia,Sr. Engineer,operational support\nPublishing\nVideo conferencing\nScheduling\nmicrosoft\nIT operations\ncisco...,1
12,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY)|-|GENERAL MANAGER (INFORMATION TECHNOLOGY),INFORMATION TECHNOLOGY\nGeneral Manager IT\nDebugging\nTools\nJ2Ee\nWindows\nApplication softwar...,2
13,International Institute of Information Technology,Technology Management- Lecturer|-|Technology Management- Assistant Professor|-|Technology Manage...,Counselor\nMentor\nTrainer\nAdvisor\nEducator\nTeaching|-|Counselor\nMentor\nTrainer\nAdvisor\nE...,77
14,Karvy Group,Head - Information Technology,Head Information Technology,1
15,Lincoln Tech,Software Engineer,Computer science\ninformation system\nSystem management\nDatabase management\nManagement systems...,1
16,MINDCRAFT TRAININGS,"Online Teacher(Hiring For PAN India location, WFH)",Application Programming\nJava\nC++\nCSS\nC\nSoftware Testing\nHTML\nManual Testing,1
17,Medinovix,Software Engineer (Fresher),Computer science\ninformation system\nSystem management\nDatabase management\nManagement systems...,1
18,MetrixLab,Security Engineer\Analyst|-|Security Engineer\Analyst,Unix\nLinux\nNetworking\nVPN\nNetwork security\nHTTP\nSelenium\nCCNA|-|Unix\nLinux\nNetworking\n...,2
19,Nisarga Information Technology Solutions Pvt Ltd,Business Development Manager,Communication Skills\nSales\nBusiness Development Management,1
20,Novartis Healthcare Pvt. Ltd.,DevSecOps & Automation Engineer,Networking\nWAN\nLAN\nActive directory\nDNS\nTroubleshooting\nRuby\nInformation technology,1
21,Overseas Information Technology,"Opening For Appian Developer/L1 or L2 MUST--Bangalore, Hyderabad, Pune|-|Urgent Opening For Appi...",appian\nL1\nL2\nlevel 2|-|Client Communication\nAgile\nScrum\nProcess Design\nJIRA\nLeadership S...,6
22,Personal Network. Ltd,Software Engineer / Sr. Software Engineer - RDBMS,Senior Design Engineer\nTechnology consulting\nNetworking\nRDBMS\nPLSQL\nPRO*C\nInformation tech...,1
23,R G F Services,AI ML Architect,Architecture\nSystem Design\nAnalytical\nHTTP\nMachine Learning\nInformation technology,1
24,Ram IT Solutions,US HR Operations Trainee | HR,IT services\nService management\nPerformance management\nInfrastructure management\nEmployee eng...,1
25,S2TECH.COM INDIA PVT LTD,NIT / IIT Freshers For Trainee - Software Engineer Immediate Position,Design\ninformation technology engineering\nCoding\nSoftware Engineering\nit engineering,1
26,SG Analytics Pvt. Ltd.,Contract To Hire - ( Secondary Research - IT/ Telecom),Telecom\nSecondary Research\nCompany Analysis\nAdvanced Excel\nIT\nReport Writing\nSWOT\nBalance...,1
27,Sahasya Global Solutions,Product Support Engineer,technical\nsoftware\nSystem programming\ntesting\nit\nTroubleshooting\nInformation technology\nP...,1
28,Stellar Information Technology Private Limited,Relationship Manager || IT Product Sales Exp. (1-4 Yrs.),CRM Sales\nIt Product Sales\nB2B Sales\nHardware Sales\nIT Sales\nIT Hardware Sales\nCloud Sales...,1
29,TERRA TECHNOLOGY,Information Technology|-|Information Technology,Unix\nService management\nglobal operations\nLinux\nAnalytical\nWindows\nCustomer service\nInfor...,2
30,TOOURS COM,Sales and Business Development - Internship,Business administration\nEconomics\nPDF\nNetworking\nWorkflow\nHTML\nAfter sales support\nB2B Sales,1
31,Thinksure Information Technology Private Limited,Dot Net Developer-Permanent|-|.Net Developer - Agreement with the Client For span of 2 Years,.Net|-|asp.net mvc\nlinq\nc#.net\nsql server\nasp net,2
32,Times World Information Technology,Area Business Manager/Project Manager,Area Business Manager/Project Manager,1
33,True Troops Consultants Private Limited,IT Freshers and Software Developers|-|IT Engineer,Java\nfresher\nC++\nEngineering graduates\nB tech freshers\nC#.Net\n.Net\nASP.Net|-|it engineer\...,2
34,Wells Fargo India Solutions Pvt. Ltd.,Systems Support Analyst 1|-|Senior Technology Specialist|-|Senior Technology Specialist|-|Techno...,SAN\nRedhat\nNetworking\nRDBMS\nShell scripting\nSSH\nWindows\nInformation technology|-|Unix\nRe...,74
35,Young India Information Technology Services (P) Lt,Syteline Techno Functional Analysts|-|Syteline Technical Developers|-|IT Sales Manager,Training\nBusiness Analyst\nTechno functional\nDesign development\nPresales\nProposal building|-...,3
36,Zyme India,Associate / Global Support Engineer,Computer science\nBusiness process\nTomcat\nLinux\nProduction support\nJBoss\nConfiguration mana...,1

#### Replace newline with comma in 'skills' attribute

In [85]:
df_jobs_agg["skills"] = df_jobs_agg["skills"].str.replace("\n",",")
df_jobs_agg

,company_name,designation,skills,number_of_positions
0,AGI INDUSTRIES PRIVATE LIMITED,it-networking-manager,"switching,hr recruiter,network engineering,information technology,software,hiring,ites,it manager",1
1,"Advanced Micro Devices, Inc.",Network-Engineer-1-1,"Telecom,Networking,WAN,Network security,CCNA,Troubleshooting,Information technology,cisco",1
2,Ayan Consultancy,Project Manager,"Project analysis,Project management,Budgeting,Information technology",1
3,BM Global Solutions,Visio Tool Expert (Freelance),"freelance,MS Visio,IT,Information Technology",1
4,CDK GLOBAL (INDIA) PRIVATE LIMITED,Automation Engineer - Python,"IT Skills,Python,Software Development,Javascript,Salesforce,Automation,Linux,Javascript",1
5,"CDK GLOBAL, LLC.",Automation Engineer - Python,"Linux,Javascript,Flex,Workflow,Perl,Digital marketing,Information technology,Automotive",1
6,Cognia Technologies,Information Technology (.Net),"assembly language,Six Sigma,JavaScript,Real Time Operating Systems,.NET,HTML,Oracle,Python",1
7,Comint Systems and Solutions Pvt Ltd,"NETWORK ENGINEERS, CUSTOMER SUPPORT ENGINEERS","Telecom,Networking,Business expansion,Electronics,Network security,Instrumentation,Support servi...",1
8,Cubic Transportation Systems India Pvt. Ltd.,Senior Software Engineer|-|Principal Lead Software Engineer|-|Senior Software Engineer,"Computer science,Hibernate,Networking,Coding,Debugging,Support services,Unit testing,Troubleshoo...",3
9,Dhruvsoft Services Pvt Ltd,Fresher / Entry Level Position For Software Engineer - Hyderabad,"Entry Level,Application Programming,Software Engineering,B.E,IT,Information Technology",1
10,Edification Technologies,Software Developer,"Angularjs,it development,software development,information technology development,Ionic Framework...",1
11,ExecBoardinAsia,Sr. Engineer,"operational support,Publishing,Video conferencing,Scheduling,microsoft,IT operations,cisco,Infor...",1
12,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY)|-|GENERAL MANAGER (INFORMATION TECHNOLOGY),"INFORMATION TECHNOLOGY,General Manager IT,Debugging,Tools,J2Ee,Windows,Application software|-|Co...",2
13,International Institute of Information Technology,Technology Management- Lecturer|-|Technology Management- Assistant Professor|-|Technology Manage...,"Counselor,Mentor,Trainer,Advisor,Educator,Teaching|-|Counselor,Mentor,Trainer,Advisor,Educator,T...",77
14,Karvy Group,Head - Information Technology,Head Information Technology,1
15,Lincoln Tech,Software Engineer,"Computer science,information system,System management,Database management,Management systems,Tim...",1
16,MINDCRAFT TRAININGS,"Online Teacher(Hiring For PAN India location, WFH)","Application Programming,Java,C++,CSS,C,Software Testing,HTML,Manual Testing",1
17,Medinovix,Software Engineer (Fresher),"Computer science,information system,System management,Database management,Management systems,Tim...",1
18,MetrixLab,Security Engineer\Analyst|-|Security Engineer\Analyst,"Unix,Linux,Networking,VPN,Network security,HTTP,Selenium,CCNA|-|Unix,Linux,Networking,VPN,Networ...",2
19,Nisarga Information Technology Solutions Pvt Ltd,Business Development Manager,"Communication Skills,Sales,Business Development Management",1
20,Novartis Healthcare Pvt. Ltd.,DevSecOps & Automation Engineer,"Networking,WAN,LAN,Active directory,DNS,Troubleshooting,Ruby,Information technology",1
21,Overseas Information Technology,"Opening For Appian Developer/L1 or L2 MUST--Bangalore, Hyderabad, Pune|-|Urgent Opening For Appi...","appian,L1,L2,level 2|-|Client Communication,Agile,Scrum,Process Design,JIRA,Leadership Skills|-|...",6
22,Personal Network. Ltd,Software Engineer / Sr. Software Engineer - RDBMS,"Senior Design Engineer,Technology consulting,Networking,RDBMS,PLSQL,PRO*C,Information technology...",1
23,R G F Services,AI ML Architect,"Architecture,System Design,Analytical,HTTP,Machine Learning,Information technology",1
24,Ram IT Solutions,US HR Operations Trainee | HR,"IT services,Service management,Performance management,Infrastructure management,Employee engagem...",1
25,S2TECH.COM INDIA PVT LTD,NIT / IIT Freshers For Trainee - Software Engineer Immediate Position,"Design,information technology engineering,Coding,Software Engineering,it engineering",1
26,SG Analytics Pvt. Ltd.,Contract To Hire - ( Secondary Research - IT/ Telecom),"Telecom,Secondary Research,Company Analysis,Advanced Excel,IT,Report Writing,SWOT,Balance Sheet",1
27,Sahasya Global Solutions,Product Support Engineer,"technical,software,System programming,testing,it,Troubleshooting,Information technology,Product ...",1
28,Stellar Information Technology Private Limited,Relationship Manager || IT Product Sales Exp. (1-4 Yrs.),"CRM Sales,It Product Sales,B2B Sales,Hardware Sales,IT Sales,IT Hardware Sales,Cloud Sales,Websi...",1
29,TERRA TECHNOLOGY,Information Technology|-|Information Technology,"Unix,Service management,global operations,Linux,Analytical,Windows,Customer service,Information ...",2
30,TOOURS COM,Sales and Business Development - Internship,"Business administration,Economics,PDF,Networking,Workflow,HTML,After sales support,B2B Sales",1
31,Thinksure Information Technology Private Limited,Dot Net Developer-Permanent|-|.Net Developer - Agreement with the Client For span of 2 Years,".Net|-|asp.net mvc,linq,c#.net,sql server,asp net",2
32,Times World Information Technology,Area Business Manager/Project Manager,Area Business Manager/Project Manager,1
33,True Troops Consultants Private Limited,IT Freshers and Software Developers|-|IT Engineer,"Java,fresher,C++,Engineering graduates,B tech freshers,C#.Net,.Net,ASP.Net|-|it engineer,Enginee...",2
34,Wells Fargo India Solutions Pvt. Ltd.,Systems Support Analyst 1|-|Senior Technology Specialist|-|Senior Technology Specialist|-|Techno...,"SAN,Redhat,Networking,RDBMS,Shell scripting,SSH,Windows,Information technology|-|Unix,Redhat Lin...",74
35,Young India Information Technology Services (P) Lt,Syteline Techno Functional Analysts|-|Syteline Technical Developers|-|IT Sales Manager,"Training,Business Analyst,Techno functional,Design development,Presales,Proposal building|-|WMS|...",3
36,Zyme India,Associate / Global Support Engineer,"Computer science,Business process,Tomcat,Linux,Production support,JBoss,Configuration management...",1

#### Add a new attribute called 'Segmentation'. Populate with "Information Technology"

In [86]:
df_jobs_agg["Segmentation"] = "Information Technology"
df_jobs_agg

,company_name,designation,skills,number_of_positions,Segmentation
0,AGI INDUSTRIES PRIVATE LIMITED,it-networking-manager,"switching,hr recruiter,network engineering,information technology,software,hiring,ites,it manager",1,Information Technology
1,"Advanced Micro Devices, Inc.",Network-Engineer-1-1,"Telecom,Networking,WAN,Network security,CCNA,Troubleshooting,Information technology,cisco",1,Information Technology
2,Ayan Consultancy,Project Manager,"Project analysis,Project management,Budgeting,Information technology",1,Information Technology
3,BM Global Solutions,Visio Tool Expert (Freelance),"freelance,MS Visio,IT,Information Technology",1,Information Technology
4,CDK GLOBAL (INDIA) PRIVATE LIMITED,Automation Engineer - Python,"IT Skills,Python,Software Development,Javascript,Salesforce,Automation,Linux,Javascript",1,Information Technology
5,"CDK GLOBAL, LLC.",Automation Engineer - Python,"Linux,Javascript,Flex,Workflow,Perl,Digital marketing,Information technology,Automotive",1,Information Technology
6,Cognia Technologies,Information Technology (.Net),"assembly language,Six Sigma,JavaScript,Real Time Operating Systems,.NET,HTML,Oracle,Python",1,Information Technology
7,Comint Systems and Solutions Pvt Ltd,"NETWORK ENGINEERS, CUSTOMER SUPPORT ENGINEERS","Telecom,Networking,Business expansion,Electronics,Network security,Instrumentation,Support servi...",1,Information Technology
8,Cubic Transportation Systems India Pvt. Ltd.,Senior Software Engineer|-|Principal Lead Software Engineer|-|Senior Software Engineer,"Computer science,Hibernate,Networking,Coding,Debugging,Support services,Unit testing,Troubleshoo...",3,Information Technology
9,Dhruvsoft Services Pvt Ltd,Fresher / Entry Level Position For Software Engineer - Hyderabad,"Entry Level,Application Programming,Software Engineering,B.E,IT,Information Technology",1,Information Technology
10,Edification Technologies,Software Developer,"Angularjs,it development,software development,information technology development,Ionic Framework...",1,Information Technology
11,ExecBoardinAsia,Sr. Engineer,"operational support,Publishing,Video conferencing,Scheduling,microsoft,IT operations,cisco,Infor...",1,Information Technology
12,Hyderabad Race Club,GENERAL MANAGER (INFORMATION TECHNOLOGY)|-|GENERAL MANAGER (INFORMATION TECHNOLOGY),"INFORMATION TECHNOLOGY,General Manager IT,Debugging,Tools,J2Ee,Windows,Application software|-|Co...",2,Information Technology
13,International Institute of Information Technology,Technology Management- Lecturer|-|Technology Management- Assistant Professor|-|Technology Manage...,"Counselor,Mentor,Trainer,Advisor,Educator,Teaching|-|Counselor,Mentor,Trainer,Advisor,Educator,T...",77,Information Technology
14,Karvy Group,Head - Information Technology,Head Information Technology,1,Information Technology
15,Lincoln Tech,Software Engineer,"Computer science,information system,System management,Database management,Management systems,Tim...",1,Information Technology
16,MINDCRAFT TRAININGS,"Online Teacher(Hiring For PAN India location, WFH)","Application Programming,Java,C++,CSS,C,Software Testing,HTML,Manual Testing",1,Information Technology
17,Medinovix,Software Engineer (Fresher),"Computer science,information system,System management,Database management,Management systems,Tim...",1,Information Technology
18,MetrixLab,Security Engineer\Analyst|-|Security Engineer\Analyst,"Unix,Linux,Networking,VPN,Network security,HTTP,Selenium,CCNA|-|Unix,Linux,Networking,VPN,Networ...",2,Information Technology
19,Nisarga Information Technology Solutions Pvt Ltd,Business Development Manager,"Communication Skills,Sales,Business Development Management",1,Information Technology
20,Novartis Healthcare Pvt. Ltd.,DevSecOps & Automation Engineer,"Networking,WAN,LAN,Active directory,DNS,Troubleshooting,Ruby,Information technology",1,Information Technology
21,Overseas Information Technology,"Opening For Appian Developer/L1 or L2 MUST--Bangalore, Hyderabad, Pune|-|Urgent Opening For Appi...","appian,L1,L2,level 2|-|Client Communication,Agile,Scrum,Process Design,JIRA,Leadership Skills|-|...",6,Information Technology
22,Personal Network. Ltd,Software Engineer / Sr. Software Engineer - RDBMS,"Senior Design Engineer,Technology consulting,Networking,RDBMS,PLSQL,PRO*C,Information technology...",1,Information Technology
23,R G F Services,AI ML Architect,"Architecture,System Design,Analytical,HTTP,Machine Learning,Information technology",1,Information Technology
24,Ram IT Solutions,US HR Operations Trainee | HR,"IT services,Service management,Performance management,Infrastructure management,Employee engagem...",1,Information Technology
25,S2TECH.COM INDIA PVT LTD,NIT / IIT Freshers For Trainee - Software Engineer Immediate Position,"Design,information technology engineering,Coding,Software Engineering,it engineering",1,Information Technology
26,SG Analytics Pvt. Ltd.,Contract To Hire - ( Secondary Research - IT/ Telecom),"Telecom,Secondary Research,Company Analysis,Advanced Excel,IT,Report Writing,SWOT,Balance Sheet",1,Information Technology
27,Sahasya Global Solutions,Product Support Engineer,"technical,software,System programming,testing,it,Troubleshooting,Information technology,Product ...",1,Information Technology
28,Stellar Information Technology Private Limited,Relationship Manager || IT Product Sales Exp. (1-4 Yrs.),"CRM Sales,It Product Sales,B2B Sales,Hardware Sales,IT Sales,IT Hardware Sales,Cloud Sales,Websi...",1,Information Technology
29,TERRA TECHNOLOGY,Information Technology|-|Information Technology,"Unix,Service management,global operations,Linux,Analytical,Windows,Customer service,Information ...",2,Information Technology
30,TOOURS COM,Sales and Business Development - Internship,"Business administration,Economics,PDF,Networking,Workflow,HTML,After sales support,B2B Sales",1,Information Technology
31,Thinksure Information Technology Private Limited,Dot Net Developer-Permanent|-|.Net Developer - Agreement with the Client For span of 2 Years,".Net|-|asp.net mvc,linq,c#.net,sql server,asp net",2,Information Technology
32,Times World Information Technology,Area Business Manager/Project Manager,Area Business Manager/Project Manager,1,Information Technology
33,True Troops Consultants Private Limited,IT Freshers and Software Developers|-|IT Engineer,"Java,fresher,C++,Engineering graduates,B tech freshers,C#.Net,.Net,ASP.Net|-|it engineer,Enginee...",2,Information Technology
34,Wells Fargo India Solutions Pvt. Ltd.,Systems Support Analyst 1|-|Senior Technology Specialist|-|Senior Technology Specialist|-|Techno...,"SAN,Redhat,Networking,RDBMS,Shell scripting,SSH,Windows,Information technology|-|Unix,Redhat Lin...",74,Information Technology
35,Young India Information Technology Services (P) Lt,Syteline Techno Functional Analysts|-|Syteline Technical Developers|-|IT Sales Manager,"Training,Business Analyst,Techno functional,Design development,Presales,Proposal building|-|WMS|...",3,Information Technology
36,Zyme India,Associate / Global Support Engineer,"Computer science,Business process,Tomcat,Linux,Production support,JBoss,Configuration management...",1,Information Technology

#### Create a final dataframe. Drop 'designation' attribute as it's not required

In [87]:
final_df = pd.DataFrame()
final_df["Name of the company"] = df_jobs_agg["company_name"]
final_df["Number of Positions"] = df_jobs_agg["number_of_positions"]
final_df["Segmentation"] = df_jobs_agg["Segmentation"]
final_df["Skills they are looking for"] = df_jobs_agg["skills"]
final_df

,Name of the company,Number of Positions,Segmentation,Skills they are looking for
0,AGI INDUSTRIES PRIVATE LIMITED,1,Information Technology,"switching,hr recruiter,network engineering,information technology,software,hiring,ites,it manager"
1,"Advanced Micro Devices, Inc.",1,Information Technology,"Telecom,Networking,WAN,Network security,CCNA,Troubleshooting,Information technology,cisco"
2,Ayan Consultancy,1,Information Technology,"Project analysis,Project management,Budgeting,Information technology"
3,BM Global Solutions,1,Information Technology,"freelance,MS Visio,IT,Information Technology"
4,CDK GLOBAL (INDIA) PRIVATE LIMITED,1,Information Technology,"IT Skills,Python,Software Development,Javascript,Salesforce,Automation,Linux,Javascript"
5,"CDK GLOBAL, LLC.",1,Information Technology,"Linux,Javascript,Flex,Workflow,Perl,Digital marketing,Information technology,Automotive"
6,Cognia Technologies,1,Information Technology,"assembly language,Six Sigma,JavaScript,Real Time Operating Systems,.NET,HTML,Oracle,Python"
7,Comint Systems and Solutions Pvt Ltd,1,Information Technology,"Telecom,Networking,Business expansion,Electronics,Network security,Instrumentation,Support servi..."
8,Cubic Transportation Systems India Pvt. Ltd.,3,Information Technology,"Computer science,Hibernate,Networking,Coding,Debugging,Support services,Unit testing,Troubleshoo..."
9,Dhruvsoft Services Pvt Ltd,1,Information Technology,"Entry Level,Application Programming,Software Engineering,B.E,IT,Information Technology"
10,Edification Technologies,1,Information Technology,"Angularjs,it development,software development,information technology development,Ionic Framework..."
11,ExecBoardinAsia,1,Information Technology,"operational support,Publishing,Video conferencing,Scheduling,microsoft,IT operations,cisco,Infor..."
12,Hyderabad Race Club,2,Information Technology,"INFORMATION TECHNOLOGY,General Manager IT,Debugging,Tools,J2Ee,Windows,Application software|-|Co..."
13,International Institute of Information Technology,77,Information Technology,"Counselor,Mentor,Trainer,Advisor,Educator,Teaching|-|Counselor,Mentor,Trainer,Advisor,Educator,T..."
14,Karvy Group,1,Information Technology,Head Information Technology
15,Lincoln Tech,1,Information Technology,"Computer science,information system,System management,Database management,Management systems,Tim..."
16,MINDCRAFT TRAININGS,1,Information Technology,"Application Programming,Java,C++,CSS,C,Software Testing,HTML,Manual Testing"
17,Medinovix,1,Information Technology,"Computer science,information system,System management,Database management,Management systems,Tim..."
18,MetrixLab,2,Information Technology,"Unix,Linux,Networking,VPN,Network security,HTTP,Selenium,CCNA|-|Unix,Linux,Networking,VPN,Networ..."
19,Nisarga Information Technology Solutions Pvt Ltd,1,Information Technology,"Communication Skills,Sales,Business Development Management"
20,Novartis Healthcare Pvt. Ltd.,1,Information Technology,"Networking,WAN,LAN,Active directory,DNS,Troubleshooting,Ruby,Information technology"
21,Overseas Information Technology,6,Information Technology,"appian,L1,L2,level 2|-|Client Communication,Agile,Scrum,Process Design,JIRA,Leadership Skills|-|..."
22,Personal Network. Ltd,1,Information Technology,"Senior Design Engineer,Technology consulting,Networking,RDBMS,PLSQL,PRO*C,Information technology..."
23,R G F Services,1,Information Technology,"Architecture,System Design,Analytical,HTTP,Machine Learning,Information technology"
24,Ram IT Solutions,1,Information Technology,"IT services,Service management,Performance management,Infrastructure management,Employee engagem..."
25,S2TECH.COM INDIA PVT LTD,1,Information Technology,"Design,information technology engineering,Coding,Software Engineering,it engineering"
26,SG Analytics Pvt. Ltd.,1,Information Technology,"Telecom,Secondary Research,Company Analysis,Advanced Excel,IT,Report Writing,SWOT,Balance Sheet"
27,Sahasya Global Solutions,1,Information Technology,"technical,software,System programming,testing,it,Troubleshooting,Information technology,Product ..."
28,Stellar Information Technology Private Limited,1,Information Technology,"CRM Sales,It Product Sales,B2B Sales,Hardware Sales,IT Sales,IT Hardware Sales,Cloud Sales,Websi..."
29,TERRA TECHNOLOGY,2,Information Technology,"Unix,Service management,global operations,Linux,Analytical,Windows,Customer service,Information ..."
30,TOOURS COM,1,Information Technology,"Business administration,Economics,PDF,Networking,Workflow,HTML,After sales support,B2B Sales"
31,Thinksure Information Technology Private Limited,2,Information Technology,".Net|-|asp.net mvc,linq,c#.net,sql server,asp net"
32,Times World Information Technology,1,Information Technology,Area Business Manager/Project Manager
33,True Troops Consultants Private Limited,2,Information Technology,"Java,fresher,C++,Engineering graduates,B tech freshers,C#.Net,.Net,ASP.Net|-|it engineer,Enginee..."
34,Wells Fargo India Solutions Pvt. Ltd.,74,Information Technology,"SAN,Redhat,Networking,RDBMS,Shell scripting,SSH,Windows,Information technology|-|Unix,Redhat Lin..."
35,Young India Information Technology Services (P) Lt,3,Information Technology,"Training,Business Analyst,Techno functional,Design development,Presales,Proposal building|-|WMS|..."
36,Zyme India,1,Information Technology,"Computer science,Business process,Tomcat,Linux,Production support,JBoss,Configuration management..."

#### Write the dataframe to CSV file

In [88]:
final_df.to_csv('./Hyderabad_Anuroop_Ajmera.csv', index=False)